=== tiendat21896/XML/ASM2/ASM2.XSD
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="ORDER">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="CUSTOMER">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="FIRSTNAME" type="xsd:string"/>
                             <xsd:element name="LASTNAME" type="xsd:string"/>
                            <xsd:element name="TELEPHONE" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="GRAND_TOTAL" type="xsd:integer"/>
                <xsd:element name="SHIPPING_ADDRESS" type="xsd:string"/>
                <xsd:element name="ITEMS">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="PRODUCT" minOccurs="1" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="NAME" type="xsd:string"/>
                                        <xsd:element name="PRICE" type="xsd:integer"/>
                                        <xsd:element name="QTY" type="xsd:integer"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

=== tiendat21896/XML/ASM2/ASM2.XML
<?xml version="1.0" encoding="UTF-8" ?>
<ORDER xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="ASM2.XSD">
    <CUSTOMER>
        <FIRSTNAME>Tony</FIRSTNAME>
        <LASTNAME>Stark</LASTNAME>
        <TELEPHONE>0989988</TELEPHONE>
    </CUSTOMER>
    <GRAND_TOTAL>1833</GRAND_TOTAL>
    <SHIPPING_ADDRESS>NO8. TON THAT THUYET</SHIPPING_ADDRESS>
    <ITEMS>
        <PRODUCT>
            <NAME>KHoai lang nuong</NAME>
            <PRICE>12</PRICE>
            <QTY>1</QTY>
        </PRODUCT>
        <PRODUCT>
            <NAME>Dau phong</NAME>
            <PRICE>12</PRICE>
            <QTY>1</QTY>
        </PRODUCT>
    </ITEMS>
</ORDER>
